<?php

add_module([
    'position'=>19,
    'name'=>'unit-kerja',
    'title'=>'Unit Kerja',
    'description'=>'Menu Untuk Mengelola Unit Kerja',
    'parent'=>false,
    'icon'=>'fa-desktop',
    'data_title'=>'Nama Unit Kerja',
    'custom_column'=>false,
    'post_parent'=>false,
    'custom_field'=> false,
    'looping'=> false,
    'looping_data'=>array(
      ['Jabatan','text'],
      ['Nama Pejabat','text'],
      ['NIP','text'],
      ['Foto','file']
    ),
    'looping_for'=> 'Silahkan Masukkan Informasi Jabatan',
    'thumbnail'=> false,
    'editor'=> true,
    'group'=>true,
    'api'=>false,
    'archive'=>false,
    'index'=>true,
    'detail'=>true,
    'operator'=>true,
    'public'=>true,
    'history'=>false,
    'auto_query'=>false,
    'auto_load'=>true,
    'crud'=>['create','read','update','delete'],
    'status'=>false,

  ]
  );
  add_module([
    'position'=>19,
    'name'=>'link',
    'title'=>'Link Terkait',
    'description'=>'Menu Untuk Mengelola Link Terkait',
    'parent'=>false,
    'icon'=>'fa-link',
    'data_title'=>'Nama Link',
    'custom_column'=>false,
    'post_parent'=>false,
    'custom_field'=> false,
    'looping'=> false,
    'looping_data'=>array(
      ['Jabatan','text'],
      ['Nama Pejabat','text'],
      ['NIP','text'],
      ['Foto','file']
    ),
    'looping_for'=> 'Silahkan Masukkan Informasi Jabatan',
    'thumbnail'=> true,
    'editor'=> false,
    'group'=>false,
    'api'=>false,
    'archive'=>false,
    'index'=>false,
    'detail'=>true,
    'operator'=>true,
    'public'=>true,
    'history'=>false,
    'auto_query'=>false,
    'auto_load'=>true,
    'crud'=>['create','read','update','delete'],
    'active' => true,

  ]
  );

  add_module([
    'position'=>19,
    'name'=>'kepegawaian',
    'title'=>'Kepegawaian',
    'description'=>'Menu Untuk Mengelola Kepegawaian',
    'parent'=>false,
    'icon'=>'fa-address-card',
    'data_title'=>'Nama Pegawai',
    'custom_column'=>'NIP',
    'post_parent'=>['Unit Kerja','unit-kerja'],
    'custom_field'=>[
      ['NIP','text','required'],
      ['Jabatan','text','required'],
      ['Pendidikan','text','required'],
    ],
    'looping'=> false,
    'looping_data'=>false,
    'looping_for'=> 'Silahkan Masukkan Informasi Jabatan',
    'thumbnail'=> true,
    'editor'=> false,
    'group'=>true,
    'api'=>false,
    'archive'=>false,
    'index'=>true,
    'detail'=>false,
    'operator'=>true,
    'public'=>true,
    'history'=>false,
    'auto_query'=>false,
    'auto_load'=>true,
    'status'=>false,
    'crud'=>['create','read','update','delete'],
    'active' => true,

  ]
  );
  add_module([
    'position'=>19,
    'name'=>'jadwal',
    'title'=>'Jadwal Roro',
    'description'=>'Menu Untuk Mengelola Jadwal Roro',
    'parent'=>false,
    'icon'=>'fa-ship',
    'data_title'=>'Periode',
    'custom_column'=>false,
    'post_parent'=>false,
    'custom_field'=>false,
    'looping'=> 'Jadwal',
    'looping_data'=>[
        ['Trip','number'],
        ['Air Putih','time'],
        ['Sungai Selari','time'],
        ['Jenis',['Air Putih BBM','Sungai Selari BBM','Umum']],
    ],
    'looping_for'=> 'Silahkan Masukkan Jadwal',
    'thumbnail'=>false,
    'editor'=> false,
    'group'=>true,
    'api'=>false,
    'archive'=>false,
    'index'=>true,
    'detail'=>false,
    'operator'=>true,
    'public'=>true,
    'history'=>false,
    'auto_query'=>false,
    'auto_load'=>true,
    'crud'=>['create','read','update','delete'],
    'active' => true,
  ]
  );
  use_module([
    'unit-kerja'=>['group'=>true],
    'sakip'=>true,
    'pengumuman'=>true,
    'jadwal'=>true,
    'kepegawaian'=>['group'=>true,'index'=>true,'detail'=>false],
]);

$config['web_type'] = "Dinas";
$config['optionable'] = ['Nama Dinas','Singkatan','Deskripsi Dinas','Alamat'];
